### ISSUE TITLE
Apron 0.9.15 compatibility

### ISSUE THREAD

**Issue by antoinemine** [ghilesZ/apronext#2]
Hi !
I'm in the process of submitting the Opam package for Apron 0.9.15.

Unfortunately, it has some breaking changes... that break Apronext. 

This is due to https://github.com/antoinemine/apron/pull/108 : following complaints about some `compare` functions in Apron not being a total order (as expected by OCaml users) these have been renamed into `cmp`  to avoid confusion. Apronext still uses these `compare` function. 

Do you see a way around this?

**Comment by ghilesZ** [comment]
Hi,
feel free to break the code, i'll manage a fix soon (in a few days)

**Comment by ghilesZ** [comment]
I have removed the references to ```Environment.compare```, i believe that was the only broken part of the code. Thanks for reporting this issue. Closed by [39610de](https://github.com/ghilesZ/apronext/commit/39610de5930e12c8d0156ed2d55fedc220f1e77d)
